import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";

export const myFont = localFont({
  src: [
    { path: "./fonts/TTNorms-Light.otf", weight: "300", style: "normal" },
    { path: "./fonts/TTNorms-Regular.otf", weight: "400", style: "normal" },
    { path: "./fonts/TTNorms-Bold.otf", weight: "700", style: "normal" },
  ],
  variable: "--font-myfont",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
